/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./admin.html",
    "./owner.html",
    "./legal.html",
    "./overlay.html",
    "./**/*.{html,js}",
  ],
  theme: {
    extend: {
      colors: {
        emerald: {
          50: '#f0fdf4',
          100: '#dcfce7',
          200: '#bbf7d0',
          300: '#86efac',
          400: '#4ade80',
          500: '#22c55e',
          600: '#16a34a',
          700: '#15803d',
          800: '#166534',
          900: '#145231',
          950: '#052e16',
        },
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'system-ui', '-apple-system', 'sans-serif'],
      },
      maxWidth: {
        '6xl': '72rem',
      },
      spacing: {
        '[52px]': '52px',
        '[68px]': '68px',
        '[76px]': '76px',
        '[88px]': '88px',
        '[100px]': '100px',
      },
    },
  },
  safelist: [
    'bg-emerald-300', 'bg-emerald-300/10', 'bg-emerald-300/20', 'bg-emerald-300/30', 'bg-emerald-300/40', 'bg-emerald-300/50', 'bg-emerald-300/[.05]',
    'border-emerald-300', 'border-emerald-300/20', 'border-emerald-300/30', 'border-emerald-300/40', 'border-emerald-300/60',
    'text-emerald-300', 'text-emerald-200', 'text-emerald-100',
    'hover:border-emerald-300/40', 'hover:text-emerald-200', 'focus:border-emerald-300/60',
    'bg-zinc-950', 'bg-zinc-900', 'bg-zinc-800', 'bg-zinc-700', 'bg-zinc-600', 'bg-zinc-500', 'bg-zinc-400', 'bg-zinc-300', 'bg-zinc-200', 'bg-zinc-100',
    'text-zinc-100', 'text-zinc-200', 'text-zinc-300', 'text-zinc-400', 'text-zinc-500', 'text-zinc-600',
    'border-zinc-700', 'border-zinc-600', 'border-zinc-500', 'border-zinc-400',
    'border-white/[.07]', 'border-white/[.08]', 'border-white/[.09]', 'border-white/10',
    'bg-white/[.05]', 'bg-white/[.08]', 'bg-white/[.12]', 'bg-white/10', 'bg-white/20', 'hover:bg-white/[.025]',
    'placeholder:text-zinc-500',
    'bg-rose-300', 'border-rose-300', 'text-rose-300', 'text-rose-200', 'bg-rose-300/10', 'bg-rose-300/[.05]', 'border-rose-300/15',
    'bg-amber-300', 'border-amber-300', 'text-amber-300', 'text-amber-100', 'bg-amber-300/20', 'bg-amber-300/[.07]',
    'grid', 'flex', 'inline-flex', 'absolute', 'relative', 'fixed', 'sticky',
    'min-h-screen', 'min-h-full', 'h-full', 'w-full', 'max-w-6xl', 'container',
    'mx-auto', 'px-4', 'px-6', 'py-3', 'py-6', 'py-12', 'py-20', 'pb-20',
    'gap-2', 'gap-3', 'gap-4', 'gap-6', 'gap-10', 'gap-x-4', 'gap-x-5', 'gap-y-5', 'gap-y-6',
    'col-span-full', 'col-span-1', 'col-span-2',
    'grid-cols-2', 'grid-cols-3', 'grid-cols-4', 'grid-cols-5',
    'text-xs', 'text-sm', 'text-base', 'text-lg', 'text-xl', 'text-2xl', 'text-4xl', 'text-5xl',
    'font-light', 'font-normal', 'font-medium', 'font-semibold', 'font-bold', 'font-extrabold',
    'tracking-tight', 'leading-7', 'leading-8', 'leading-[1.15]',
    'rounded', 'rounded-lg', 'rounded-xl', 'rounded-2xl', 'rounded-full',
    'border', 'border-b', 'border-dashed', 'border-2',
    'overflow-hidden', 'overflow-y-auto', 'shrink-0', 'sr-only', 'hidden', 'block', 'inline-block',
    'items-center', 'justify-center', 'items-end', 'justify-between', 'items-start',
    'truncate', 'min-w-0', 'object-cover', 'bg-cover', 'bg-center',
    'backdrop-blur-md', 'backdrop-blur-lg', 'tabular-nums', 'cursor-pointer',
    'transform', 'scale-98', 'translate-y-6', '-translate-y-1', '-translate-y-10', '-translate-y-12',
    '-mt-10', '-mt-12', 'mt-1', 'mt-1.5', 'mt-2', 'mt-3', 'mt-4', 'mt-6', 'mt-10',
    'mb-2', 'mb-3', 'mb-4', 'mb-5', 'aspect-[4/3]',
    'md:grid-cols-[minmax(0,1fr)_minmax(250px,360px)]', 'md:gap-10', 'md:pb-10', 'md:pb-12',
    'sm:text-5xl', 'sm:text-4xl', 'sm:text-2xl', 'sm:text-base', 'sm:text-lg', 'sm:text-[11px]',
    'sm:leading-[1.15]', 'sm:px-4', 'sm:px-6', 'sm:px-7', 'sm:pt-4', 'sm:pt-14',
    'sm:gap-4', 'sm:gap-6', 'sm:grid-cols-3', 'sm:block', 'sm:hidden',
    'lg:grid-cols-4', 'xl:grid-cols-5',
    'pointer-events-none', 'transition', 'transition-all', 'duration-300', 'ease-in-out',
    'group', 'hover:scale-100', 'active:transform', 'active:scale-98',
    'focus-visible:outline', 'focus-visible:outline-2', 'animate-pulse',
  ],
  plugins: [],
}

